language: python
script: python mysite/manage.py test polls
python:
  - "3.6.5"
services:
  - postgresql

before_script:
  - psql -c "CREATE USER <%= ENV['DB_USER'] %> WITH PASSWORD <%= ENV['DB_PASSWORD'] %>;" -U postgres
  - psql -c "CREATE DATABASE mysite;" -U <%= ENV['DB_USER'] %>
  - psql -c "ALTER ROLE <%= ENV['DB_USER'] %> SET client_encoding TO 'utf8';" -U <%= ENV['DB_USER'] %>
  - psql -c "ALTER ROLE <%= ENV['DB_USER'] %> SET default_transaction_isolation TO 'read committed';" -U <%= ENV['DB_USER'] %>
  - psql -c "ALTER ROLE <%= ENV['DB_USER'] %> SET timezone TO 'UTC';" -U <%= ENV['DB_USER'] %>
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE mysite TO <%= ENV['DB_USER'] %>;" -U <%= ENV['DB_USER'] %>
